GET http://127.0.0.1:8000/products/ HTTP/1.1

###

GET http://127.0.0.1:8000/products/2/ HTTP/1.1

###

DELETE http://127.0.0.1:8000/products/2/ HTTP/1.1

###

PUT http://127.0.0.1:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMzU5Nzc4LCJpYXQiOjE3NDEzNTk0NzgsImp0aSI6IjgzMzhmNGZmMDBmOTQ4NTY5Mjc2NDMxZTBjNTg0MjFhIiwidXNlcl9pZCI6M30.OcN-bjFMtvvIkmVL_jXG3vcKGMkAABwBHfCie6PuUtU

{
    "name": "Television",
    "price": 300.00,
    "stock": 14, 
    "description": "An Amazing new TV"
}

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMzU2NDE0LCJpYXQiOjE3NDEzNTYxMTQsImp0aSI6ImMyNjk3OGVmNThlMzRhYjlhNjg2ZTkwNzdlZDM3ZThmIiwidXNlcl9pZCI6M30.OE0l2XrFwqyHP8GLo0KtYXb_EONt23gwhd_oiVa09IY

{
    "name": "Television",
    "price": 300.00,
    "stock": 14, 
    "description": "An Amazing new TV"
}

### 

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "lincxx", 
    "password": "test"
}

###
 
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MTQ0MzQ1MiwiaWF0IjoxNzQxMzU3MDUyLCJqdGkiOiJhMjg4ZTg1NjBhMWE0ZWRiOGQxZWEyMGU0Mjc3Yjk3NiIsInVzZXJfaWQiOjN9.I6oHMcqn5JjEm30g31QSZ-LcYxLCptJfCdqpHzKOjOM"
}

### 

GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxMzU2NDE0LCJpYXQiOjE3NDEzNTYxMTQsImp0aSI6ImMyNjk3OGVmNThlMzRhYjlhNjg2ZTkwNzdlZDM3ZThmIiwidXNlcl9pZCI6M30.OE0l2XrFwqyHP8GLo0KtYXb_EONt23gwhd_oiVa09IY

###  


GET http://127.0.0.1:8000/orders?status=confirmed HTTP/1.1

###

